### ISSUE TITLE
autoSize column width doesn't account for fontSize

### ISSUE THREAD

**Issue by rodney757** [dhatim/fastexcel#35]
If I set the cell style fontSize to say (14), the autoSizing that happens will not take into account the font size, and the cell will be partially hidden.

**Comment by ochedru** [comment]
Fixed by PR #34.

**Comment by rodney757** [comment]
PR #34 doesn't fix this issue.

It does allow column width to be set manually, but it would be nice if the auto-width algorithm took into account the font size which it currently doesn't.

**Comment by rzymek** [comment]
I suppose this line needs some tweaking: https://github.com/dhatim/fastexcel/blob/ee98567d289f4e5d12a9506f757ed2fc367c53c6/fastexcel-writer/src/main/java/org/dhatim/fastexcel/Worksheet.java#L431

@ochedru What does this formula actually do? Why exactly those numbers (7,10,256)?

**Comment by rzymek** [comment]
This may be of some assistance:
https://github.com/apache/poi/blob/9f07780bac1b86bd65be33857fc33d7fa50f0072/src/ooxml/java/org/apache/poi/xssf/usermodel/XSSFSheet.java#L553

Looks fairly complex in Apache POI...

**Comment by ochedru** [comment]
As far as I can remember, I used a simplified version of what Apache POI does... My primary goal was to have something "good enough" with the default font, but time proves it was probably not that good 😄

**Comment by vSrkth** [comment]
Is there any update for auto maximum column width for excel, 
As i sees based on text length and text font this size going to vary, if we use column.width() it will overrides the last value.

**Comment by EwaTrzemzalska** [comment]
+1, same issue here, when I change font size for 14, some column are partially hidden
